export enum ActionType {
  NONE = "NONE",
  ACTIVATE_VISOR_RENDERER = "ACTIVATE_VISOR_RENDERER",
  ACTIVATE_RGB_SCENE = "ACTIVATE_RGB_SCENE",
  PLAY_VIDEO = "PLAY_VIDEO",
  FACE_EXPRESSION = "FACE_EXPRESSION",
  ACTIVATE_FACE_RGB_EFFECT = "ACTIVATE_FACE_RGB_EFFECT",
  DISABLE_RGB = "DISABLE_RGB",
  STOP_VIDEO = "STOP_VIDEO",
  RUN_ACTION_SET = "RUN_ACTION_SET",
  RESET_BOOP_SENSOR_COUNTER = "RESET_BOOP_SENSOR_COUNTER",
  TOGGLE_BOOP_SENSOR = "TOGGLE_BOOP_SENSOR",
}
