name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        folder: [frontend, backend, remote_worker]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install dependencies
        run: npm install
        working-directory: ${{ matrix.folder }}

      - name: Run security audit
        run: npm audit --audit-level=high
        working-directory: ${{ matrix.folder }}

      - name: Run linter
        run: npm run lint
        working-directory: ${{ matrix.folder }}

      - name: Build project
        run: npm run build
        working-directory: ${{ matrix.folder }}