name: Daily NPM Audit

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  audit:
    name: Run NPM Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Dependencies for Node-Gyp
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev
  

      - name: Audit Frontend
        working-directory: frontend
        run: |
          npm install
          npm audit --json > audit-frontend.json || true

      - name: Audit Backend
        working-directory: backend
        run: |
          npm install
          npm audit --json > audit-backend.json || true

      - name: Audit Remote Worker
        working-directory: remote_worker
        run: |
          npm install
          npm audit --json > audit-remote-worker.json || true

      - name: Upload Audit Reports
        uses: actions/upload-artifact@v4
        with:
          name: npm-audit-reports
          path: |
            frontend/audit-frontend.json
            backend/audit-backend.json
            remote_worker/audit-remote-worker.json

      - name: Check for Moderate or Higher Vulnerabilities
        run: |
          MODERATE_COUNT=$(jq '.advisories | to_entries | map(select(.value.severity == "moderate")) | length' frontend/audit-frontend.json backend/audit-backend.json remote_worker/audit-remote-worker.json | paste -sd+ - | bc)
          HIGH_COUNT=$(jq '.advisories | to_entries | map(select(.value.severity == "high")) | length' frontend/audit-frontend.json backend/audit-backend.json remote_worker/audit-remote-worker.json | paste -sd+ - | bc)
          CRITICAL_COUNT=$(jq '.advisories | to_entries | map(select(.value.severity == "critical")) | length' frontend/audit-frontend.json backend/audit-backend.json remote_worker/audit-remote-worker.json | paste -sd+ - | bc)
          
          echo "Moderate vulnerabilities: $MODERATE_COUNT"
          echo "High vulnerabilities: $HIGH_COUNT"
          echo "Critical vulnerabilities: $CRITICAL_COUNT"

          if [[ $MODERATE_COUNT -gt 0 || $HIGH_COUNT -gt 0 || $CRITICAL_COUNT -gt 0 ]]; then
            echo "🚨 Found vulnerabilities of severity moderate or higher!"
            exit 1
          fi