name: Daily NPM Audit

on:
  schedule:
    - cron: '0 5 * * *'
  workflow_dispatch:

jobs:
  audit:
    name: Run NPM Audit
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 'lts/*'

      - name: Install Dependencies for Node-Gyp
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libcairo2-dev libpango1.0-dev libjpeg-dev libgif-dev librsvg2-dev

      - name: Audit Frontend
        working-directory: frontend
        run: |
          npm install
          npm audit --audit-level=high

      - name: Audit Backend
        working-directory: backend
        run: |
          npm install
          npm audit --audit-level=high

      - name: Audit Remote Worker
        working-directory: remote_worker
        run: |
          npm install
          npm audit --audit-level=high
